project:
  type: website
  resources:
    - zonkarta/**
  render:
    - "*.qmd"
    - "sektioner/*.qmd"
    - "!zonkarta/"

website:
  title: "Samhällsbyggnad i Halland"
  navbar: false
  page-navigation: false
  back-to-top-navigation: false
